/**
 * ************************************
 *
 * @module  actionTypes.js
 * @author
 * @date
 * @description Action Type Constants
 *
 * ************************************
 */

export const types = {
  FETCH_SHOUTOUTS_REQUEST: 'FETCH_SHOUTOUTS_REQUEST',
  FETCH_SHOUTOUTS_SUCCESS: 'FETCH_SHOUTOUTS_SUCCESS',
  FETCH_SHOUTOUTS_FAILURE: 'FETCH_SHOUTOUTS_FAILURE',

  POST_SHOUTOUT_REQUEST: 'POST_SHOUTOUT_REQUEST',
  POST_SHOUTOUT_SUCCESS: 'POST_SHOUTOUT_SUCCESS',
  POST_SHOUTOUT_FAILURE: 'POST_SHOUTOUT_FAILURE',

  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  ADD_COMMENT: 'ADD_COMMENT',
};
